#!/bin/bash
# =============================================================================
# apps/catalog.sh — AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Run: python3 scripts/gen_catalog_sh.py
# Total apps: 103
# =============================================================================

# All app IDs (space-separated)
CATALOG_IDS=("qbittorrent" "transmission" "deluge" "sabnzbd" "nzbget" "jdownloader2" "pyload" "aria2" "pinchflat" "qbitrr" "prowlarr" "radarr" "sonarr" "lidarr" "bazarr" "whisparr" "readarr" "mylar3" "doplarr" "boxarr" "recyclarr" "unpackerr" "notifiarr" "jellyfin" "plex" "emby" "navidrome" "kavita" "komga" "audiobookshelf" "tdarr" "fileflows" "handbrake" "kometa" "wizarr" "jellystat" "seerr" "ombi" "requestrr" "tautulli" "flaresolverr" "grafana" "prometheus" "uptime_kuma" "netdata" "glances" "dozzle" "portainer" "watchtower" "scrutiny" "speedtest" "homer" "homarr" "dasherr" "flame" "heimdall" "organizr" "traefik" "npm" "caddy" "swag" "wireguard" "tailscale" "gluetun" "wg_easy" "adguardhome" "pihole" "technitium" "n8n" "huginn" "changedetection" "node_red" "activepieces" "nextcloud" "filebrowser" "syncthing" "paperless_ngx" "immich" "photoprism" "stirling_pdf" "vaultwarden" "authentik" "authelia" "crowdsec" "ntfy" "gotify" "matrix_synapse" "gitea" "code_server" "drone" "mariadb" "postgres" "redis" "mongodb" "mealie" "grocy" "freshrss" "wallabag" "linkding" "calibre_web" "actual_budget" "cyberchef" "arrhub_webui")

# Associative arrays — one entry per app
declare -A APP_NAME APP_CATEGORY APP_IMAGE APP_DESCRIPTION APP_PORTS APP_ICON APP_NOTES

APP_NAME["qbittorrent"]="qBittorrent"
APP_CATEGORY["qbittorrent"]="Downloaders"
APP_IMAGE["qbittorrent"]="lscr.io/linuxserver/qbittorrent:latest"
APP_DESCRIPTION["qbittorrent"]="Popular, feature-rich BitTorrent client with a clean web UI."
APP_PORTS["qbittorrent"]="8080:8080 6881:6881 6881:6881/udp"
APP_ICON["qbittorrent"]="\u2b07\ufe0f"
APP_NOTES["qbittorrent"]=""

APP_NAME["transmission"]="Transmission"
APP_CATEGORY["transmission"]="Downloaders"
APP_IMAGE["transmission"]="lscr.io/linuxserver/transmission:latest"
APP_DESCRIPTION["transmission"]="Lightweight, cross-platform BitTorrent client."
APP_PORTS["transmission"]="9091:9091 51413:51413 51413:51413/udp"
APP_ICON["transmission"]="\u2b07\ufe0f"
APP_NOTES["transmission"]=""

APP_NAME["deluge"]="Deluge"
APP_CATEGORY["deluge"]="Downloaders"
APP_IMAGE["deluge"]="lscr.io/linuxserver/deluge:latest"
APP_DESCRIPTION["deluge"]="Highly extensible BitTorrent client with a rich plugin ecosystem."
APP_PORTS["deluge"]="8112:8112 6881:6881 6881:6881/udp"
APP_ICON["deluge"]="\u2b07\ufe0f"
APP_NOTES["deluge"]=""

APP_NAME["sabnzbd"]="SABnzbd"
APP_CATEGORY["sabnzbd"]="Downloaders"
APP_IMAGE["sabnzbd"]="lscr.io/linuxserver/sabnzbd:latest"
APP_DESCRIPTION["sabnzbd"]="Best-in-class Usenet NZB downloader with post-processing."
APP_PORTS["sabnzbd"]="8090:8080"
APP_ICON["sabnzbd"]="\u2b07\ufe0f"
APP_NOTES["sabnzbd"]=""

APP_NAME["nzbget"]="NZBGet"
APP_CATEGORY["nzbget"]="Downloaders"
APP_IMAGE["nzbget"]="lscr.io/linuxserver/nzbget:latest"
APP_DESCRIPTION["nzbget"]="Efficient, highly optimised Usenet downloader."
APP_PORTS["nzbget"]="6789:6789"
APP_ICON["nzbget"]="\u2b07\ufe0f"
APP_NOTES["nzbget"]=""

APP_NAME["jdownloader2"]="JDownloader 2"
APP_CATEGORY["jdownloader2"]="Downloaders"
APP_IMAGE["jdownloader2"]="jlesage/jdownloader-2:latest"
APP_DESCRIPTION["jdownloader2"]="Java-based download manager supporting 100s of file hosters."
APP_PORTS["jdownloader2"]="5800:5800"
APP_ICON["jdownloader2"]="\u2b07\ufe0f"
APP_NOTES["jdownloader2"]=""

APP_NAME["pyload"]="pyLoad"
APP_CATEGORY["pyload"]="Downloaders"
APP_IMAGE["pyload"]="ghcr.io/pyload/pyload:latest"
APP_DESCRIPTION["pyload"]="Free, open-source download manager written in Python."
APP_PORTS["pyload"]="8000:8000"
APP_ICON["pyload"]="\u2b07\ufe0f"
APP_NOTES["pyload"]=""

APP_NAME["aria2"]="Aria2 Pro"
APP_CATEGORY["aria2"]="Downloaders"
APP_IMAGE["aria2"]="p3terx/aria2-pro:latest"
APP_DESCRIPTION["aria2"]="Multi-protocol & multi-source command-line download utility."
APP_PORTS["aria2"]="6800:6800 6888:6888 6888:6888/udp"
APP_ICON["aria2"]="\u2b07\ufe0f"
APP_NOTES["aria2"]=""

APP_NAME["pinchflat"]="Pinchflat"
APP_CATEGORY["pinchflat"]="Downloaders"
APP_IMAGE["pinchflat"]="ghcr.io/kieraneglin/pinchflat:latest"
APP_DESCRIPTION["pinchflat"]="Self-hosted YouTube and media subscription manager with automatic downloads."
APP_PORTS["pinchflat"]="8945:8945"
APP_ICON["pinchflat"]="\ud83d\udcfa"
APP_NOTES["pinchflat"]=""

APP_NAME["qbitrr"]="qbitrr"
APP_CATEGORY["qbitrr"]="Downloaders"
APP_IMAGE["qbitrr"]="feramance/qbitrr:latest"
APP_DESCRIPTION["qbitrr"]="Companion app for qBittorrent, Radarr, and Sonarr \u2014 manages queue and removes stalled downloads."
APP_PORTS["qbitrr"]="6969:6969"
APP_ICON["qbitrr"]="\ud83d\udd27"
APP_NOTES["qbitrr"]=""

APP_NAME["prowlarr"]="Prowlarr"
APP_CATEGORY["prowlarr"]="ARR Suite"
APP_IMAGE["prowlarr"]="lscr.io/linuxserver/prowlarr:latest"
APP_DESCRIPTION["prowlarr"]="Indexer manager and proxy supporting many torrent and Usenet trackers."
APP_PORTS["prowlarr"]="9696:9696"
APP_ICON["prowlarr"]="\ud83d\udce6"
APP_NOTES["prowlarr"]=""

APP_NAME["radarr"]="Radarr"
APP_CATEGORY["radarr"]="ARR Suite"
APP_IMAGE["radarr"]="lscr.io/linuxserver/radarr:latest"
APP_DESCRIPTION["radarr"]="Movie collection manager. Integrates with download clients and media servers."
APP_PORTS["radarr"]="7878:7878"
APP_ICON["radarr"]="\ud83d\udce6"
APP_NOTES["radarr"]=""

APP_NAME["sonarr"]="Sonarr"
APP_CATEGORY["sonarr"]="ARR Suite"
APP_IMAGE["sonarr"]="lscr.io/linuxserver/sonarr:latest"
APP_DESCRIPTION["sonarr"]="Smart PVR for TV shows. Searches, downloads, and manages your TV library."
APP_PORTS["sonarr"]="8989:8989"
APP_ICON["sonarr"]="\ud83d\udce6"
APP_NOTES["sonarr"]=""

APP_NAME["lidarr"]="Lidarr"
APP_CATEGORY["lidarr"]="ARR Suite"
APP_IMAGE["lidarr"]="lscr.io/linuxserver/lidarr:latest"
APP_DESCRIPTION["lidarr"]="Music collection manager. Automatically downloads music to your library."
APP_PORTS["lidarr"]="8686:8686"
APP_ICON["lidarr"]="\ud83d\udce6"
APP_NOTES["lidarr"]=""

APP_NAME["bazarr"]="Bazarr"
APP_CATEGORY["bazarr"]="ARR Suite"
APP_IMAGE["bazarr"]="lscr.io/linuxserver/bazarr:latest"
APP_DESCRIPTION["bazarr"]="Companion app to Sonarr and Radarr for automatic subtitle management."
APP_PORTS["bazarr"]="6767:6767"
APP_ICON["bazarr"]="\ud83d\udce6"
APP_NOTES["bazarr"]=""

APP_NAME["whisparr"]="Whisparr"
APP_CATEGORY["whisparr"]="ARR Suite"
APP_IMAGE["whisparr"]="ghcr.io/hotio/whisparr:nightly"
APP_DESCRIPTION["whisparr"]="Adult content collection manager. Part of the ARR family."
APP_PORTS["whisparr"]="6969:6969"
APP_ICON["whisparr"]="\ud83d\udce6"
APP_NOTES["whisparr"]=""

APP_NAME["readarr"]="Readarr"
APP_CATEGORY["readarr"]="ARR Suite"
APP_IMAGE["readarr"]="ghcr.io/hotio/readarr:nightly"
APP_DESCRIPTION["readarr"]="Book/eBook collection manager. Like Sonarr but for books."
APP_PORTS["readarr"]="8787:8787"
APP_ICON["readarr"]="\ud83d\udce6"
APP_NOTES["readarr"]=""

APP_NAME["mylar3"]="Mylar3"
APP_CATEGORY["mylar3"]="ARR Suite"
APP_IMAGE["mylar3"]="lscr.io/linuxserver/mylar3:latest"
APP_DESCRIPTION["mylar3"]="Automated comic book downloader for CBZ/CBR files."
APP_PORTS["mylar3"]="8090:8090"
APP_ICON["mylar3"]="\ud83d\udce6"
APP_NOTES["mylar3"]=""

APP_NAME["doplarr"]="Doplarr"
APP_CATEGORY["doplarr"]="ARR Suite"
APP_IMAGE["doplarr"]="lscr.io/linuxserver/doplarr:latest"
APP_DESCRIPTION["doplarr"]="Discord bot for requesting media via Overseerr, Radarr, and Sonarr."
APP_PORTS["doplarr"]=""
APP_ICON["doplarr"]="\ud83d\udce6"
APP_NOTES["doplarr"]="Requires Discord bot token and Sonarr/Radarr API keys post-deploy."

APP_NAME["boxarr"]="Boxarr"
APP_CATEGORY["boxarr"]="ARR Suite"
APP_IMAGE["boxarr"]="nicholasammann/boxarr:latest"
APP_DESCRIPTION["boxarr"]="Physical media collection manager \u2014 track box sets alongside your digital library."
APP_PORTS["boxarr"]="3579:3000"
APP_ICON["boxarr"]="\ud83d\udce6"
APP_NOTES["boxarr"]="Tracks physical box sets (DVDs/Blu-rays) alongside your Radarr/Sonarr library."

APP_NAME["recyclarr"]="Recyclarr"
APP_CATEGORY["recyclarr"]="ARR Suite"
APP_IMAGE["recyclarr"]="ghcr.io/recyclarr/recyclarr:latest"
APP_DESCRIPTION["recyclarr"]="Syncs TRaSH Guide quality profiles and settings to Sonarr and Radarr."
APP_PORTS["recyclarr"]=""
APP_ICON["recyclarr"]="\ud83d\udce6"
APP_NOTES["recyclarr"]=""

APP_NAME["unpackerr"]="Unpackerr"
APP_CATEGORY["unpackerr"]="ARR Suite"
APP_IMAGE["unpackerr"]="golift/unpackerr:latest"
APP_DESCRIPTION["unpackerr"]="Extracts downloaded archives for Radarr, Sonarr, Lidarr, and Readarr."
APP_PORTS["unpackerr"]=""
APP_ICON["unpackerr"]="\ud83d\udce6"
APP_NOTES["unpackerr"]=""

APP_NAME["notifiarr"]="Notifiarr"
APP_CATEGORY["notifiarr"]="ARR Suite"
APP_IMAGE["notifiarr"]="golift/notifiarr:latest"
APP_DESCRIPTION["notifiarr"]="Unified notification and integration hub for your ARR stack."
APP_PORTS["notifiarr"]="5454:5454"
APP_ICON["notifiarr"]="\ud83d\udce6"
APP_NOTES["notifiarr"]=""

APP_NAME["jellyfin"]="Jellyfin"
APP_CATEGORY["jellyfin"]="Media Servers"
APP_IMAGE["jellyfin"]="jellyfin/jellyfin:latest"
APP_DESCRIPTION["jellyfin"]="Free, open-source media server. No subscriptions, no tracking."
APP_PORTS["jellyfin"]="8096:8096 8920:8920"
APP_ICON["jellyfin"]="\ud83c\udfac"
APP_NOTES["jellyfin"]=""

APP_NAME["plex"]="Plex Media Server"
APP_CATEGORY["plex"]="Media Servers"
APP_IMAGE["plex"]="plexinc/pms-docker:latest"
APP_DESCRIPTION["plex"]="Feature-rich media server with apps for almost every device."
APP_PORTS["plex"]="32400:32400"
APP_ICON["plex"]="\ud83c\udfac"
APP_NOTES["plex"]=""

APP_NAME["emby"]="Emby"
APP_CATEGORY["emby"]="Media Servers"
APP_IMAGE["emby"]="emby/embyserver:latest"
APP_DESCRIPTION["emby"]="Personal media server with live TV, DVR, and subtitle support."
APP_PORTS["emby"]="8096:8096 8920:8920"
APP_ICON["emby"]="\ud83c\udfac"
APP_NOTES["emby"]=""

APP_NAME["navidrome"]="Navidrome"
APP_CATEGORY["navidrome"]="Media Servers"
APP_IMAGE["navidrome"]="deluan/navidrome:latest"
APP_DESCRIPTION["navidrome"]="Modern, lightweight music server compatible with Subsonic/Airsonic clients."
APP_PORTS["navidrome"]="4533:4533"
APP_ICON["navidrome"]="\ud83c\udfac"
APP_NOTES["navidrome"]=""

APP_NAME["kavita"]="Kavita"
APP_CATEGORY["kavita"]="Media Servers"
APP_IMAGE["kavita"]="kizaing/kavita:latest"
APP_DESCRIPTION["kavita"]="Manga, comics, and book server with reading progress tracking."
APP_PORTS["kavita"]="5000:5000"
APP_ICON["kavita"]="\ud83c\udfac"
APP_NOTES["kavita"]=""

APP_NAME["komga"]="Komga"
APP_CATEGORY["komga"]="Media Servers"
APP_IMAGE["komga"]="gotson/komga:latest"
APP_DESCRIPTION["komga"]="Media server for comics, manga, and graphic novels with OPDS support."
APP_PORTS["komga"]="8081:8080"
APP_ICON["komga"]="\ud83c\udfac"
APP_NOTES["komga"]=""

APP_NAME["audiobookshelf"]="Audiobookshelf"
APP_CATEGORY["audiobookshelf"]="Media Servers"
APP_IMAGE["audiobookshelf"]="ghcr.io/advplyr/audiobookshelf:latest"
APP_DESCRIPTION["audiobookshelf"]="Self-hosted audiobook and podcast server with app support."
APP_PORTS["audiobookshelf"]="13378:80"
APP_ICON["audiobookshelf"]="\ud83c\udfac"
APP_NOTES["audiobookshelf"]=""

APP_NAME["tdarr"]="Tdarr"
APP_CATEGORY["tdarr"]="Media Tools"
APP_IMAGE["tdarr"]="ghcr.io/haveagitgat/tdarr:latest"
APP_DESCRIPTION["tdarr"]="Distributed media transcoding automation with health checks and GPU support."
APP_PORTS["tdarr"]="8265:8265 8266:8266"
APP_ICON["tdarr"]="\ud83d\udce6"
APP_NOTES["tdarr"]=""

APP_NAME["fileflows"]="FileFlows"
APP_CATEGORY["fileflows"]="Media Tools"
APP_IMAGE["fileflows"]="revenz/fileflows:latest"
APP_DESCRIPTION["fileflows"]="File processing system with a visual flow editor for media conversion."
APP_PORTS["fileflows"]="19200:5000"
APP_ICON["fileflows"]="\ud83d\udce6"
APP_NOTES["fileflows"]=""

APP_NAME["handbrake"]="HandBrake"
APP_CATEGORY["handbrake"]="Media Tools"
APP_IMAGE["handbrake"]="jlesage/handbrake:latest"
APP_DESCRIPTION["handbrake"]="Video transcoder GUI accessible via web browser."
APP_PORTS["handbrake"]="5800:5800"
APP_ICON["handbrake"]="\ud83d\udce6"
APP_NOTES["handbrake"]=""

APP_NAME["kometa"]="Kometa (Plex Meta Manager)"
APP_CATEGORY["kometa"]="Media Tools"
APP_IMAGE["kometa"]="kometateam/kometa:latest"
APP_DESCRIPTION["kometa"]="Automates Plex collection and metadata management using YAML configs."
APP_PORTS["kometa"]=""
APP_ICON["kometa"]="\ud83d\udce6"
APP_NOTES["kometa"]="Configure Plex connection in /config/config.yml before starting."

APP_NAME["wizarr"]="Wizarr"
APP_CATEGORY["wizarr"]="Media Tools"
APP_IMAGE["wizarr"]="ghcr.io/wizarrrr/wizarr:latest"
APP_DESCRIPTION["wizarr"]="Automatic user invitation and onboarding system for Plex and Jellyfin."
APP_PORTS["wizarr"]="5690:5690"
APP_ICON["wizarr"]="\ud83d\udce6"
APP_NOTES["wizarr"]=""

APP_NAME["jellystat"]="Jellystat"
APP_CATEGORY["jellystat"]="Media Tools"
APP_IMAGE["jellystat"]="cyfershepard/jellystat:latest"
APP_DESCRIPTION["jellystat"]="Statistics and activity tracking dashboard for Jellyfin."
APP_PORTS["jellystat"]="3005:3000"
APP_ICON["jellystat"]="\ud83d\udce6"
APP_NOTES["jellystat"]=""

APP_NAME["seerr"]="Seerr"
APP_CATEGORY["seerr"]="Request Tools"
APP_IMAGE["seerr"]="ghcr.io/seerr-team/seerr:latest"
APP_DESCRIPTION["seerr"]="Unified media request manager \u2014 successor to Jellyseerr and Overseerr."
APP_PORTS["seerr"]="5055:5055"
APP_ICON["seerr"]="\ud83c\udfa5"
APP_NOTES["seerr"]="Replaces Overseerr and Jellyseerr. Supports Jellyfin, Plex, and Emby."

APP_NAME["ombi"]="Ombi"
APP_CATEGORY["ombi"]="Request Tools"
APP_IMAGE["ombi"]="lscr.io/linuxserver/ombi:latest"
APP_DESCRIPTION["ombi"]="User-facing media request portal for Plex, Emby, and Jellyfin."
APP_PORTS["ombi"]="3579:3579"
APP_ICON["ombi"]="\ud83c\udfa5"
APP_NOTES["ombi"]=""

APP_NAME["requestrr"]="Requestrr"
APP_CATEGORY["requestrr"]="Request Tools"
APP_IMAGE["requestrr"]="lscr.io/linuxserver/requestrr:latest"
APP_DESCRIPTION["requestrr"]="Discord bot for requesting movies and TV shows via Radarr/Sonarr."
APP_PORTS["requestrr"]="4545:4545"
APP_ICON["requestrr"]="\ud83c\udfa5"
APP_NOTES["requestrr"]=""

APP_NAME["tautulli"]="Tautulli"
APP_CATEGORY["tautulli"]="Request Tools"
APP_IMAGE["tautulli"]="lscr.io/linuxserver/tautulli:latest"
APP_DESCRIPTION["tautulli"]="Monitoring and tracking tool for Plex Media Server."
APP_PORTS["tautulli"]="8181:8181"
APP_ICON["tautulli"]="\ud83c\udfa5"
APP_NOTES["tautulli"]=""

APP_NAME["flaresolverr"]="FlareSolverr"
APP_CATEGORY["flaresolverr"]="Request Tools"
APP_IMAGE["flaresolverr"]="ghcr.io/flaresolverr/flaresolverr:latest"
APP_DESCRIPTION["flaresolverr"]="Proxy server to bypass Cloudflare and DDoS-Guard protection."
APP_PORTS["flaresolverr"]="8191:8191"
APP_ICON["flaresolverr"]="\ud83c\udfa5"
APP_NOTES["flaresolverr"]=""

APP_NAME["grafana"]="Grafana"
APP_CATEGORY["grafana"]="Monitoring"
APP_IMAGE["grafana"]="grafana/grafana:latest"
APP_DESCRIPTION["grafana"]="Open observability platform for metrics, logs, and traces visualization."
APP_PORTS["grafana"]="3000:3000"
APP_ICON["grafana"]="\ud83d\udcc8"
APP_NOTES["grafana"]=""

APP_NAME["prometheus"]="Prometheus"
APP_CATEGORY["prometheus"]="Monitoring"
APP_IMAGE["prometheus"]="prom/prometheus:latest"
APP_DESCRIPTION["prometheus"]="Systems monitoring and alerting toolkit with time-series database."
APP_PORTS["prometheus"]="9090:9090"
APP_ICON["prometheus"]="\ud83d\udcc8"
APP_NOTES["prometheus"]=""

APP_NAME["uptime_kuma"]="Uptime Kuma"
APP_CATEGORY["uptime_kuma"]="Monitoring"
APP_IMAGE["uptime_kuma"]="louislam/uptime-kuma:latest"
APP_DESCRIPTION["uptime_kuma"]="Fancy self-hosted monitoring tool with status pages and notifications."
APP_PORTS["uptime_kuma"]="3001:3001"
APP_ICON["uptime_kuma"]="\ud83d\udcc8"
APP_NOTES["uptime_kuma"]=""

APP_NAME["netdata"]="Netdata"
APP_CATEGORY["netdata"]="Monitoring"
APP_IMAGE["netdata"]="netdata/netdata:latest"
APP_DESCRIPTION["netdata"]="Real-time, high-resolution system performance monitoring."
APP_PORTS["netdata"]="19999:19999"
APP_ICON["netdata"]="\ud83d\udcc8"
APP_NOTES["netdata"]=""

APP_NAME["glances"]="Glances"
APP_CATEGORY["glances"]="Monitoring"
APP_IMAGE["glances"]="nicolargo/glances:latest"
APP_DESCRIPTION["glances"]="Cross-platform system monitoring tool with a web interface."
APP_PORTS["glances"]="61208:61208"
APP_ICON["glances"]="\ud83d\udcc8"
APP_NOTES["glances"]=""

APP_NAME["dozzle"]="Dozzle"
APP_CATEGORY["dozzle"]="Monitoring"
APP_IMAGE["dozzle"]="amir20/dozzle:latest"
APP_DESCRIPTION["dozzle"]="Realtime Docker log viewer with a clean, searchable web interface."
APP_PORTS["dozzle"]="8888:8080"
APP_ICON["dozzle"]="\ud83d\udcc8"
APP_NOTES["dozzle"]=""

APP_NAME["portainer"]="Portainer CE"
APP_CATEGORY["portainer"]="Monitoring"
APP_IMAGE["portainer"]="portainer/portainer-ce:latest"
APP_DESCRIPTION["portainer"]="Docker management GUI with stacks, container management, and user roles."
APP_PORTS["portainer"]="9000:9000 9443:9443"
APP_ICON["portainer"]="\ud83d\udcc8"
APP_NOTES["portainer"]=""

APP_NAME["watchtower"]="Watchtower"
APP_CATEGORY["watchtower"]="Monitoring"
APP_IMAGE["watchtower"]="containrrr/watchtower:latest"
APP_DESCRIPTION["watchtower"]="Automatically updates running Docker containers when new images are available."
APP_PORTS["watchtower"]=""
APP_ICON["watchtower"]="\ud83d\udcc8"
APP_NOTES["watchtower"]=""

APP_NAME["scrutiny"]="Scrutiny"
APP_CATEGORY["scrutiny"]="Monitoring"
APP_IMAGE["scrutiny"]="ghcr.io/analogj/scrutiny:master-omnibus"
APP_DESCRIPTION["scrutiny"]="Hard drive health dashboard using S.M.A.R.T. data with alerts."
APP_PORTS["scrutiny"]="8080:8080"
APP_ICON["scrutiny"]="\ud83d\udcc8"
APP_NOTES["scrutiny"]=""

APP_NAME["speedtest"]="Speedtest Tracker"
APP_CATEGORY["speedtest"]="Monitoring"
APP_IMAGE["speedtest"]="lscr.io/linuxserver/speedtest-tracker:latest"
APP_DESCRIPTION["speedtest"]="Self-hosted internet speed test tracker with historical graphing."
APP_PORTS["speedtest"]="8765:80"
APP_ICON["speedtest"]="\ud83d\udcc8"
APP_NOTES["speedtest"]=""

APP_NAME["homer"]="Homer"
APP_CATEGORY["homer"]="Dashboards"
APP_IMAGE["homer"]="ghcr.io/bastienwirtz/homer:latest"
APP_DESCRIPTION["homer"]="Simple, static homepage for your homelab services."
APP_PORTS["homer"]="8085:8080"
APP_ICON["homer"]="\ud83d\udcca"
APP_NOTES["homer"]=""

APP_NAME["homarr"]="Homarr"
APP_CATEGORY["homarr"]="Dashboards"
APP_IMAGE["homarr"]="ghcr.io/ajnart/homarr:latest"
APP_DESCRIPTION["homarr"]="Sleek, modern dashboard with drag-and-drop, service integrations, and widgets."
APP_PORTS["homarr"]="7575:7575"
APP_ICON["homarr"]="\ud83d\udcca"
APP_NOTES["homarr"]=""

APP_NAME["dasherr"]="Dasherr"
APP_CATEGORY["dasherr"]="Dashboards"
APP_IMAGE["dasherr"]="ghcr.io/erwin-kok/dasherr:latest"
APP_DESCRIPTION["dasherr"]="Minimal, lightweight app dashboard with customizable layout."
APP_PORTS["dasherr"]="3080:3080"
APP_ICON["dasherr"]="\ud83d\udcca"
APP_NOTES["dasherr"]=""

APP_NAME["flame"]="Flame"
APP_CATEGORY["flame"]="Dashboards"
APP_IMAGE["flame"]="pawelmalak/flame:latest"
APP_DESCRIPTION["flame"]="Self-hosted startpage and application dashboard with bookmarks."
APP_PORTS["flame"]="5005:5005"
APP_ICON["flame"]="\ud83d\udcca"
APP_NOTES["flame"]=""

APP_NAME["heimdall"]="Heimdall"
APP_CATEGORY["heimdall"]="Dashboards"
APP_IMAGE["heimdall"]="lscr.io/linuxserver/heimdall:latest"
APP_DESCRIPTION["heimdall"]="Application dashboard with search functionality and enhanced app tiles."
APP_PORTS["heimdall"]="8086:80 8443:443"
APP_ICON["heimdall"]="\ud83d\udcca"
APP_NOTES["heimdall"]=""

APP_NAME["organizr"]="Organizr"
APP_CATEGORY["organizr"]="Dashboards"
APP_IMAGE["organizr"]="organizr/organizr:latest"
APP_DESCRIPTION["organizr"]="HTPC/homelab organizer with tabbed interface and user authentication."
APP_PORTS["organizr"]="8089:80"
APP_ICON["organizr"]="\ud83d\udcca"
APP_NOTES["organizr"]=""

APP_NAME["traefik"]="Traefik"
APP_CATEGORY["traefik"]="Reverse Proxies"
APP_IMAGE["traefik"]="traefik:latest"
APP_DESCRIPTION["traefik"]="Cloud-native reverse proxy and load balancer with auto SSL."
APP_PORTS["traefik"]="80:80 443:443 8888:8080"
APP_ICON["traefik"]="\ud83d\udce6"
APP_NOTES["traefik"]="Requires traefik.yml config in {CONFIG}/traefik/ before starting."

APP_NAME["npm"]="Nginx Proxy Manager"
APP_CATEGORY["npm"]="Reverse Proxies"
APP_IMAGE["npm"]="jc21/nginx-proxy-manager:latest"
APP_DESCRIPTION["npm"]="Easiest way to manage Nginx proxy hosts with SSL via Let's Encrypt."
APP_PORTS["npm"]="80:80 443:443 81:81"
APP_ICON["npm"]="\ud83d\udce6"
APP_NOTES["npm"]=""

APP_NAME["caddy"]="Caddy"
APP_CATEGORY["caddy"]="Reverse Proxies"
APP_IMAGE["caddy"]="caddy:latest"
APP_DESCRIPTION["caddy"]="Modern web server with automatic HTTPS, simple configuration."
APP_PORTS["caddy"]="80:80 443:443"
APP_ICON["caddy"]="\ud83d\udce6"
APP_NOTES["caddy"]=""

APP_NAME["swag"]="SWAG"
APP_CATEGORY["swag"]="Reverse Proxies"
APP_IMAGE["swag"]="lscr.io/linuxserver/swag:latest"
APP_DESCRIPTION["swag"]="Secure Web Application Gateway: Nginx + Certbot + Fail2ban in one container."
APP_PORTS["swag"]="443:443 80:80"
APP_ICON["swag"]="\ud83d\udce6"
APP_NOTES["swag"]="Set URL, SUBDOMAINS, and VALIDATION env vars before starting."

APP_NAME["wireguard"]="WireGuard"
APP_CATEGORY["wireguard"]="VPN & Network"
APP_IMAGE["wireguard"]="lscr.io/linuxserver/wireguard:latest"
APP_DESCRIPTION["wireguard"]="Fast, modern VPN tunnel. Use as a VPN server or client."
APP_PORTS["wireguard"]="51820:51820/udp"
APP_ICON["wireguard"]="\ud83c\udf10"
APP_NOTES["wireguard"]=""

APP_NAME["tailscale"]="Tailscale"
APP_CATEGORY["tailscale"]="VPN & Network"
APP_IMAGE["tailscale"]="tailscale/tailscale:latest"
APP_DESCRIPTION["tailscale"]="Zero-config mesh VPN built on WireGuard. Connect all your devices."
APP_PORTS["tailscale"]=""
APP_ICON["tailscale"]="\ud83c\udf10"
APP_NOTES["tailscale"]="Set TS_AUTHKEY from your Tailscale admin console before starting."

APP_NAME["gluetun"]="Gluetun"
APP_CATEGORY["gluetun"]="VPN & Network"
APP_IMAGE["gluetun"]="qmcgaw/gluetun:latest"
APP_DESCRIPTION["gluetun"]="VPN client container for 20+ providers. Route other containers through it."
APP_PORTS["gluetun"]="8888:8888"
APP_ICON["gluetun"]="\ud83c\udf10"
APP_NOTES["gluetun"]="Set VPN_SERVICE_PROVIDER and credentials before starting."

APP_NAME["wg_easy"]="WG-Easy"
APP_CATEGORY["wg_easy"]="VPN & Network"
APP_IMAGE["wg_easy"]="ghcr.io/wg-easy/wg-easy:latest"
APP_DESCRIPTION["wg_easy"]="Easiest WireGuard VPN server with a beautiful web UI for peer management."
APP_PORTS["wg_easy"]="51820:51820/udp 51821:51821"
APP_ICON["wg_easy"]="\ud83c\udf10"
APP_NOTES["wg_easy"]="Set WG_HOST to your server's public IP or domain."

APP_NAME["adguardhome"]="AdGuard Home"
APP_CATEGORY["adguardhome"]="VPN & Network"
APP_IMAGE["adguardhome"]="adguard/adguardhome:latest"
APP_DESCRIPTION["adguardhome"]="Network-wide ad and tracker blocking DNS server."
APP_PORTS["adguardhome"]="53:53 53:53/udp 8082:3000"
APP_ICON["adguardhome"]="\ud83c\udf10"
APP_NOTES["adguardhome"]="Port 53 may conflict with systemd-resolved. Disable it first."

APP_NAME["pihole"]="Pi-hole"
APP_CATEGORY["pihole"]="VPN & Network"
APP_IMAGE["pihole"]="pihole/pihole:latest"
APP_DESCRIPTION["pihole"]="DNS-based ad blocker for your entire network."
APP_PORTS["pihole"]="53:53 53:53/udp 8083:80"
APP_ICON["pihole"]="\ud83c\udf10"
APP_NOTES["pihole"]=""

APP_NAME["technitium"]="Technitium DNS"
APP_CATEGORY["technitium"]="VPN & Network"
APP_IMAGE["technitium"]="technitium/dns-server:latest"
APP_DESCRIPTION["technitium"]="Self-hosted authoritative DNS server with ad blocking and split horizon."
APP_PORTS["technitium"]="5380:5380 53:53 53:53/udp"
APP_ICON["technitium"]="\ud83c\udf10"
APP_NOTES["technitium"]=""

APP_NAME["n8n"]="n8n"
APP_CATEGORY["n8n"]="Automation"
APP_IMAGE["n8n"]="docker.n8n.io/n8nio/n8n:latest"
APP_DESCRIPTION["n8n"]="Workflow automation tool with 350+ integrations. Like Zapier, self-hosted."
APP_PORTS["n8n"]="5678:5678"
APP_ICON["n8n"]="\ud83d\udce6"
APP_NOTES["n8n"]=""

APP_NAME["huginn"]="Huginn"
APP_CATEGORY["huginn"]="Automation"
APP_IMAGE["huginn"]="ghcr.io/huginn/huginn:latest"
APP_DESCRIPTION["huginn"]="Create agents that monitor the web and act on your behalf."
APP_PORTS["huginn"]="3007:3000"
APP_ICON["huginn"]="\ud83d\udce6"
APP_NOTES["huginn"]=""

APP_NAME["changedetection"]="Changedetection.io"
APP_CATEGORY["changedetection"]="Automation"
APP_IMAGE["changedetection"]="ghcr.io/dgtlmoon/changedetection.io:latest"
APP_DESCRIPTION["changedetection"]="Monitor websites for changes and receive notifications."
APP_PORTS["changedetection"]="5000:5000"
APP_ICON["changedetection"]="\ud83d\udce6"
APP_NOTES["changedetection"]=""

APP_NAME["node_red"]="Node-RED"
APP_CATEGORY["node_red"]="Automation"
APP_IMAGE["node_red"]="nodered/node-red:latest"
APP_DESCRIPTION["node_red"]="Flow-based programming for visual wiring of IoT hardware and APIs."
APP_PORTS["node_red"]="1880:1880"
APP_ICON["node_red"]="\ud83d\udce6"
APP_NOTES["node_red"]=""

APP_NAME["activepieces"]="Activepieces"
APP_CATEGORY["activepieces"]="Automation"
APP_IMAGE["activepieces"]="activepieces/activepieces:latest"
APP_DESCRIPTION["activepieces"]="Open-source Zapier alternative with no-code automation flows."
APP_PORTS["activepieces"]="8096:80"
APP_ICON["activepieces"]="\ud83d\udce6"
APP_NOTES["activepieces"]=""

APP_NAME["nextcloud"]="Nextcloud"
APP_CATEGORY["nextcloud"]="File & Cloud"
APP_IMAGE["nextcloud"]="nextcloud:latest"
APP_DESCRIPTION["nextcloud"]="Self-hosted productivity platform: files, calendar, contacts, and more."
APP_PORTS["nextcloud"]="8093:80"
APP_ICON["nextcloud"]="\ud83d\udce6"
APP_NOTES["nextcloud"]=""

APP_NAME["filebrowser"]="File Browser"
APP_CATEGORY["filebrowser"]="File & Cloud"
APP_IMAGE["filebrowser"]="filebrowser/filebrowser:latest"
APP_DESCRIPTION["filebrowser"]="Web-based file manager with user management and sharing."
APP_PORTS["filebrowser"]="8084:80"
APP_ICON["filebrowser"]="\ud83d\udce6"
APP_NOTES["filebrowser"]=""

APP_NAME["syncthing"]="Syncthing"
APP_CATEGORY["syncthing"]="File & Cloud"
APP_IMAGE["syncthing"]="lscr.io/linuxserver/syncthing:latest"
APP_DESCRIPTION["syncthing"]="Continuous file synchronization between devices. No cloud required."
APP_PORTS["syncthing"]="8384:8384 22000:22000 21027:21027/udp"
APP_ICON["syncthing"]="\ud83d\udce6"
APP_NOTES["syncthing"]=""

APP_NAME["paperless_ngx"]="Paperless-ngx"
APP_CATEGORY["paperless_ngx"]="File & Cloud"
APP_IMAGE["paperless_ngx"]="ghcr.io/paperless-ngx/paperless-ngx:latest"
APP_DESCRIPTION["paperless_ngx"]="Document management system that transforms scans into searchable documents."
APP_PORTS["paperless_ngx"]="8010:8000"
APP_ICON["paperless_ngx"]="\ud83d\udce6"
APP_NOTES["paperless_ngx"]="For full functionality, add a Redis container and set PAPERLESS_REDIS."

APP_NAME["immich"]="Immich"
APP_CATEGORY["immich"]="File & Cloud"
APP_IMAGE["immich"]="ghcr.io/immich-app/immich-server:release"
APP_DESCRIPTION["immich"]="High-performance self-hosted photo and video backup solution."
APP_PORTS["immich"]="2283:3001"
APP_ICON["immich"]="\ud83d\udce6"
APP_NOTES["immich"]=""

APP_NAME["photoprism"]="PhotoPrism"
APP_CATEGORY["photoprism"]="File & Cloud"
APP_IMAGE["photoprism"]="photoprism/photoprism:latest"
APP_DESCRIPTION["photoprism"]="AI-powered photo management with face recognition and geo-tagging."
APP_PORTS["photoprism"]="2342:2342"
APP_ICON["photoprism"]="\ud83d\udce6"
APP_NOTES["photoprism"]=""

APP_NAME["stirling_pdf"]="Stirling PDF"
APP_CATEGORY["stirling_pdf"]="File & Cloud"
APP_IMAGE["stirling_pdf"]="frooodle/s-pdf:latest"
APP_DESCRIPTION["stirling_pdf"]="Locally hosted web-based PDF manipulation tool with 30+ operations."
APP_PORTS["stirling_pdf"]="8094:8080"
APP_ICON["stirling_pdf"]="\ud83d\udce6"
APP_NOTES["stirling_pdf"]=""

APP_NAME["vaultwarden"]="Vaultwarden"
APP_CATEGORY["vaultwarden"]="Security"
APP_IMAGE["vaultwarden"]="vaultwarden/server:latest"
APP_DESCRIPTION["vaultwarden"]="Unofficial Bitwarden-compatible password manager server. Lightweight."
APP_PORTS["vaultwarden"]="8087:80"
APP_ICON["vaultwarden"]="\ud83d\udce6"
APP_NOTES["vaultwarden"]=""

APP_NAME["authentik"]="Authentik"
APP_CATEGORY["authentik"]="Security"
APP_IMAGE["authentik"]="ghcr.io/goauthentik/server:latest"
APP_DESCRIPTION["authentik"]="Open-source identity provider with SSO, OAuth2, and LDAP support."
APP_PORTS["authentik"]="9000:9000 9443:9443"
APP_ICON["authentik"]="\ud83d\udce6"
APP_NOTES["authentik"]=""

APP_NAME["authelia"]="Authelia"
APP_CATEGORY["authelia"]="Security"
APP_IMAGE["authelia"]="authelia/authelia:latest"
APP_DESCRIPTION["authelia"]="Open-source authentication and authorization server with 2FA/MFA."
APP_PORTS["authelia"]="9091:9091"
APP_ICON["authelia"]="\ud83d\udce6"
APP_NOTES["authelia"]="Requires configuration.yml in {CONFIG}/authelia/ before starting."

APP_NAME["crowdsec"]="CrowdSec"
APP_CATEGORY["crowdsec"]="Security"
APP_IMAGE["crowdsec"]="crowdsecurity/crowdsec:latest"
APP_DESCRIPTION["crowdsec"]="Crowd-sourced security engine that detects and blocks malicious IPs."
APP_PORTS["crowdsec"]=""
APP_ICON["crowdsec"]="\ud83d\udce6"
APP_NOTES["crowdsec"]=""

APP_NAME["ntfy"]="ntfy"
APP_CATEGORY["ntfy"]="Communication"
APP_IMAGE["ntfy"]="binwiederhier/ntfy:latest"
APP_DESCRIPTION["ntfy"]="Simple HTTP-based pub-sub notification service. Push to any device."
APP_PORTS["ntfy"]="2586:80"
APP_ICON["ntfy"]="\ud83d\udce6"
APP_NOTES["ntfy"]=""

APP_NAME["gotify"]="Gotify"
APP_CATEGORY["gotify"]="Communication"
APP_IMAGE["gotify"]="gotify/server:latest"
APP_DESCRIPTION["gotify"]="Simple server for sending and receiving notification messages."
APP_PORTS["gotify"]="2587:80"
APP_ICON["gotify"]="\ud83d\udce6"
APP_NOTES["gotify"]=""

APP_NAME["matrix_synapse"]="Matrix Synapse"
APP_CATEGORY["matrix_synapse"]="Communication"
APP_IMAGE["matrix_synapse"]="matrixdotorg/synapse:latest"
APP_DESCRIPTION["matrix_synapse"]="Open, decentralized real-time communication server."
APP_PORTS["matrix_synapse"]="8448:8448"
APP_ICON["matrix_synapse"]="\ud83d\udce6"
APP_NOTES["matrix_synapse"]="Generate config first: docker run --rm -v {CONFIG}/matrix:/data -e SYNAPSE_SERVER_NAME=matrix.yourdomain.com matrixdotorg/synapse:latest generate"

APP_NAME["gitea"]="Gitea"
APP_CATEGORY["gitea"]="Development"
APP_IMAGE["gitea"]="gitea/gitea:latest"
APP_DESCRIPTION["gitea"]="Lightweight self-hosted Git service. Like GitHub, locally."
APP_PORTS["gitea"]="3030:3000 2222:22"
APP_ICON["gitea"]="\ud83d\udce6"
APP_NOTES["gitea"]=""

APP_NAME["code_server"]="Code Server"
APP_CATEGORY["code_server"]="Development"
APP_IMAGE["code_server"]="lscr.io/linuxserver/code-server:latest"
APP_DESCRIPTION["code_server"]="Run VS Code in the browser on your server. Code from anywhere."
APP_PORTS["code_server"]="8888:8443"
APP_ICON["code_server"]="\ud83d\udce6"
APP_NOTES["code_server"]=""

APP_NAME["drone"]="Drone CI"
APP_CATEGORY["drone"]="Development"
APP_IMAGE["drone"]="drone/drone:latest"
APP_DESCRIPTION["drone"]="Container-native continuous integration and delivery platform."
APP_PORTS["drone"]="8097:80"
APP_ICON["drone"]="\ud83d\udce6"
APP_NOTES["drone"]=""

APP_NAME["mariadb"]="MariaDB"
APP_CATEGORY["mariadb"]="Databases"
APP_IMAGE["mariadb"]="lscr.io/linuxserver/mariadb:latest"
APP_DESCRIPTION["mariadb"]="MySQL-compatible relational database. Used by many homelab apps."
APP_PORTS["mariadb"]=""
APP_ICON["mariadb"]="\ud83d\uddc4\ufe0f"
APP_NOTES["mariadb"]=""

APP_NAME["postgres"]="PostgreSQL"
APP_CATEGORY["postgres"]="Databases"
APP_IMAGE["postgres"]="postgres:latest"
APP_DESCRIPTION["postgres"]="Advanced open-source relational database with JSON support."
APP_PORTS["postgres"]="5432:5432"
APP_ICON["postgres"]="\ud83d\uddc4\ufe0f"
APP_NOTES["postgres"]=""

APP_NAME["redis"]="Redis"
APP_CATEGORY["redis"]="Databases"
APP_IMAGE["redis"]="redis:alpine"
APP_DESCRIPTION["redis"]="In-memory data structure store. Used as cache/message broker."
APP_PORTS["redis"]="6379:6379"
APP_ICON["redis"]="\ud83d\uddc4\ufe0f"
APP_NOTES["redis"]=""

APP_NAME["mongodb"]="MongoDB"
APP_CATEGORY["mongodb"]="Databases"
APP_IMAGE["mongodb"]="mongo:latest"
APP_DESCRIPTION["mongodb"]="Document-oriented NoSQL database for flexible data storage."
APP_PORTS["mongodb"]="27017:27017"
APP_ICON["mongodb"]="\ud83d\uddc4\ufe0f"
APP_NOTES["mongodb"]=""

APP_NAME["mealie"]="Mealie"
APP_CATEGORY["mealie"]="Home & Misc"
APP_IMAGE["mealie"]="ghcr.io/mealie-recipes/mealie:latest"
APP_DESCRIPTION["mealie"]="Self-hosted recipe manager and meal planner with import from any URL."
APP_PORTS["mealie"]="9003:9000"
APP_ICON["mealie"]="\ud83d\udce6"
APP_NOTES["mealie"]=""

APP_NAME["grocy"]="Grocy"
APP_CATEGORY["grocy"]="Home & Misc"
APP_IMAGE["grocy"]="lscr.io/linuxserver/grocy:latest"
APP_DESCRIPTION["grocy"]="Grocery and household management system with barcode scanning."
APP_PORTS["grocy"]="9283:80"
APP_ICON["grocy"]="\ud83d\udce6"
APP_NOTES["grocy"]=""

APP_NAME["freshrss"]="FreshRSS"
APP_CATEGORY["freshrss"]="Home & Misc"
APP_IMAGE["freshrss"]="freshrss/freshrss:latest"
APP_DESCRIPTION["freshrss"]="Self-hosted RSS feed aggregator with multi-user support."
APP_PORTS["freshrss"]="8092:80"
APP_ICON["freshrss"]="\ud83d\udce6"
APP_NOTES["freshrss"]=""

APP_NAME["wallabag"]="Wallabag"
APP_CATEGORY["wallabag"]="Home & Misc"
APP_IMAGE["wallabag"]="wallabag/wallabag:latest"
APP_DESCRIPTION["wallabag"]="Self-hosted read-it-later application with offline access."
APP_PORTS["wallabag"]="8095:80"
APP_ICON["wallabag"]="\ud83d\udce6"
APP_NOTES["wallabag"]=""

APP_NAME["linkding"]="Linkding"
APP_CATEGORY["linkding"]="Home & Misc"
APP_IMAGE["linkding"]="sissbruecker/linkding:latest"
APP_DESCRIPTION["linkding"]="Self-hosted bookmark manager with tags, search, and browser extensions."
APP_PORTS["linkding"]="9099:9090"
APP_ICON["linkding"]="\ud83d\udce6"
APP_NOTES["linkding"]=""

APP_NAME["calibre_web"]="Calibre-Web"
APP_CATEGORY["calibre_web"]="Home & Misc"
APP_IMAGE["calibre_web"]="lscr.io/linuxserver/calibre-web:latest"
APP_DESCRIPTION["calibre_web"]="Web-based eBook library browser and reader with OPDS support."
APP_PORTS["calibre_web"]="8083:8083"
APP_ICON["calibre_web"]="\ud83d\udce6"
APP_NOTES["calibre_web"]=""

APP_NAME["actual_budget"]="Actual Budget"
APP_CATEGORY["actual_budget"]="Home & Misc"
APP_IMAGE["actual_budget"]="actualbudget/actual-server:latest"
APP_DESCRIPTION["actual_budget"]="Self-hosted personal finance app. Local-first budgeting that syncs."
APP_PORTS["actual_budget"]="5006:5006"
APP_ICON["actual_budget"]="\ud83d\udce6"
APP_NOTES["actual_budget"]=""

APP_NAME["cyberchef"]="CyberChef"
APP_CATEGORY["cyberchef"]="Home & Misc"
APP_IMAGE["cyberchef"]="mpepping/cyberchef:latest"
APP_DESCRIPTION["cyberchef"]="The Cyber Swiss Army Knife. Encode, decode, encrypt, analyse data in the browser."
APP_PORTS["cyberchef"]="8098:8000"
APP_ICON["cyberchef"]="\ud83d\udce6"
APP_NOTES["cyberchef"]=""

APP_NAME["arrhub_webui"]="ArrHub WebUI"
APP_CATEGORY["arrhub_webui"]="ArrHub"
APP_IMAGE["arrhub_webui"]="arrhub-webui:local"
APP_DESCRIPTION["arrhub_webui"]="Built-in server monitoring and Docker management dashboard on port 9999."
APP_PORTS["arrhub_webui"]="9999:9999"
APP_ICON["arrhub_webui"]="\ud83d\udce6"
APP_NOTES["arrhub_webui"]="Built from local Dockerfile. Run 'media \u2192 WebUI Control \u2192 Rebuild' after updates."

# Helper: get all apps in a category
catalog_apps_in_category() {
    local cat="$1"
    local result=()
    for id in "${CATALOG_IDS[@]}"; do
        if [[ "${APP_CATEGORY[$id]}" == "$cat" ]]; then
            result+=("$id")
        fi
    done
    echo "${result[@]}"
}

# Helper: list unique categories
catalog_categories() {
    local -A seen
    for id in "${CATALOG_IDS[@]}"; do
        local cat="${APP_CATEGORY[$id]}"
        if [[ -z "${seen[$cat]+x}" ]]; then
            echo "$cat"
            seen[$cat]=1
        fi
    done
}
